### ISSUE TITLE
I installed python-nozomi using VS code, but when I tried to run Example Usage, an error occurred.

### ISSUE THREAD

**Issue by e1e1111e1e** [Alfa-Q/python-nozomi#14]
「PS C:\Users\user\Desktop\VS> & C:/Users/user/AppData/Local/Programs/Python/Python37/python.exe c:/Users/user/Desktop/VS/2023-3-15/.VScode/download1.py
missing value for field "imageurl"
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\dacite\core.py", line 72, in from_dict
    value = get_default_value_for_field(field, field_type)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\dacite\dataclasses.py", line 22, in get_default_value_for_field
    raise DefaultValueNotFoundError()
dacite.dataclasses.DefaultValueNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\nozomi\api.py", line 36, in get_post
    return from_dict(data_class=Post, data=post_data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\dacite\core.py", line 76, in from_dict
    raise MissingValueError(field.name)
dacite.exceptions.MissingValueError: missing value for field "imageurl"
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\dacite\core.py", line 72, in from_dict
    value = get_default_value_for_field(field, field_type)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\dacite\dataclasses.py", line 22, in get_default_value_for_field
    raise DefaultValueNotFoundError()
dacite.dataclasses.DefaultValueNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/user/Desktop/VS/2023-3-15/.VScode/download1.py", line 7, in <module>
    post = api.get_post(url)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\nozomi\api.py", line 36, in get_post
    return from_dict(data_class=Post, data=post_data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\dacite\core.py", line 76, in from_dict
    raise MissingValueError(field.name)
dacite.exceptions.MissingValueError: missing value for field "imageurl"」

I am not very familiar with programming languages and I am not sure where I went wrong

**Comment by Alfa-Q** [comment]
Hello, thanks for reporting this issue!  A new version will be going out sometime this week that should fix these errors.
