### ISSUE TITLE
Missing value for field "favorites" / Posts containing more then one image DLs first but ignores the rest!

### ISSUE THREAD

**Issue by Linden10** [Alfa-Q/python-nozomi#7]
I've been using your example script to download all the posts from a tag and it works nicely...
But they're some issues I've encountered...

First issue, whenever I use this to download posts, the script crashes with this error:

```
PS C:\Users\***\Downloads\test> python ..\nozomi-dl.py
missing value for field "favorites"
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dacite\core.py", line 59, in from_dict
    field_data = data[field.name]
KeyError: 'favorites'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dacite\core.py", line 71, in from_dict
    value = get_default_value_for_field(field)
  File "C:\Users\***\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dacite\dataclasses.py", line 21, in get_default_value_for_field
    raise DefaultValueNotFoundError()
dacite.dataclasses.DefaultValueNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nozomi\api.py", line 43, in get_posts
    yield from_dict(data_class=Post, data=post_data)
  File "C:\Users\***\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dacite\core.py", line 75, in from_dict
    raise MissingValueError(field.name)
dacite.exceptions.MissingValueError: missing value for field "favorites"
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dacite\core.py", line 59, in from_dict
    field_data = data[field.name]
KeyError: 'favorites'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dacite\core.py", line 71, in from_dict
    value = get_default_value_for_field(field)
  File "C:\Users\***\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dacite\dataclasses.py", line 21, in get_default_value_for_field
    raise DefaultValueNotFoundError()
dacite.dataclasses.DefaultValueNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..\nozomi-dl.py", line 8, in <module>
    for post in api.get_posts(positive_tags):
  File "C:\Users\***\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nozomi\api.py", line 43, in get_posts
    yield from_dict(data_class=Post, data=post_data)
  File "C:\Users\***\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dacite\core.py", line 75, in from_dict
    raise MissingValueError(field.name)
dacite.exceptions.MissingValueError: missing value for field "favorites"
```

I found a temporarily solution for the first issue thanks to @styler00dollar, they forked and removed the "source_int" and "favorites" code from the data.py file which resolved the crashing!

However this is still an issue in the original script so I wanted to bring this up to ya!

As for the second issue, many posts contain more then one image in them but are ignored when downloaded!

For example, this post (NSFW): https://nozomi.la/post/25937459.html#pixiv_id_31112502

Contains five images in it. The script will only download the first image in a post but not the other ones in it...
Ah...this is the only issue that stops this script from being perfect! >.<

I hope I explained things well! 
If you can resolve these issues somehow, please do tell and thank you Alfa-Q for helping and creating this script!

**Comment by Alfa-Q** [comment]
Hey @Linden10, thank you for opening a new issue for this Python package!  I'll go ahead and look into it later today or tomorrow.  Should be fixed within a day or two.

**Comment by Linden10** [comment]
Thanks, hope it's not too hard to figure out! ^_^

**Comment by Alfa-Q** [comment]
@Linden10 This is fixed in the latest release, please run ```pip install python-nozomi --upgrade```

the `api.download_media()` function has been updated to download all images for a post.

you can also now retrieve a single post with URL instead of tags via ```api.get_post()```

the following code should now work for downloading all images in a post:
```python3
post = api.get_post("https://nozomi.la/post/25937459.html#pixiv_id_31112502")
image_names = api.download_media(post, Path.cwd())
```

please open another github issue if you are having new issues or have any suggestions!
